import React, {useEffect, useRef, useState} from 'react';
import Hls from 'hls.js';
import { ImmersiveField } from './ImmersiveField';
import { CosmicCity } from './CosmicCity';
const stream='https://stream.mux.com/Aa02T7oM1wH5Mk5EEVDYhbZ1ChcdhRsS2m1NYyx4Ua1g.m3u8';
export function CosmicVideo({footer=false,motion}){
 const ref=useRef(null);
 useEffect(()=>{const video=ref.current;if(motion===false||(motion===undefined&&matchMedia('(prefers-reduced-motion: reduce)').matches))return;let hls;if(video.canPlayType('application/vnd.apple.mpegurl'))video.src=stream;else if(Hls.isSupported()){hls=new Hls({maxMaxBufferLength:30});hls.loadSource(stream);hls.attachMedia(video);}let inView=true;const play=()=>{if(inView)video.play().catch(()=>{});};const observer=new IntersectionObserver(([entry])=>{inView=entry.isIntersecting;if(inView)play();else video.pause();});observer.observe(video);video.addEventListener('canplay',play);return()=>{observer.disconnect();video.removeEventListener('canplay',play);hls?.destroy();video.removeAttribute('src');video.load();};},[motion]);
 return <div className={'cosmic-background'+(footer?' flipped':'')} aria-hidden="true"><video ref={ref} muted autoPlay loop playsInline poster="https://image.mux.com/Aa02T7oM1wH5Mk5EEVDYhbZ1ChcdhRsS2m1NYyx4Ua1g/thumbnail.jpg?time=3&width=1920"/><div className="video-shade"/></div>;
}
export function CosmicHero(){const host=useRef(null);const [immersive,setImmersive]=useState(()=>{try{return localStorage.getItem('cosmic-immersion')!=='off';}catch{return true;}});const [role,setRole]=useState(0);useEffect(()=>{if(!immersive)return;const timer=setInterval(()=>setRole(n=>(n+1)%3),2600);return()=>clearInterval(timer);},[immersive]);return <section ref={host} className="hero" id="home" data-motion={immersive?'full':'quiet'}><CosmicCity/><ImmersiveField host={host} enabled={immersive}/><button className="immersion-toggle" aria-pressed={immersive} onClick={()=>setImmersive(value=>{try{localStorage.setItem('cosmic-immersion',value?'off':'on');}catch{}return !value;})}>{immersive?'沉浸动效 · ON':'沉浸动效 · OFF'}</button><div className="hero-depth"><div className="hero-content"><span className="hero-eyebrow entrance">PERSONAL PORTFOLIO / 2026</span><h1 className="entrance"><span className="hero-name">Bingbing Fan</span><span>樊冰冰</span></h1><div className="hero-role entrance">Exploring the intersection of <em key={role}>{['AI & Product','Design & Technology','Data & People'][role]}</em></div><p className="hero-description entrance">从城市空间到数字产品<br/>理解人的需求，探索 AI 的可能。</p><div className="hero-actions entrance"><a className="button primary" href="#work">探索作品 <span>↗</span></a><a className="button secondary" href="#contact">Say hello <span>↗</span></a></div></div></div><a href="#work" className="scroll-indicator"><span>SCROLL TO EXPLORE</span><i/></a><span className="hero-corner left">AI PRODUCT · AIGC · SPATIAL INTELLIGENCE</span><span className="hero-corner right">THOUGHTFULLY BUILT, HUMAN FIRST.</span></section>}
export function CosmicNav(){const [active,setActive]=useState(location.hash||'#home');useEffect(()=>{const hash=()=>setActive(location.hash||'#home');addEventListener('hashchange',hash);return()=>removeEventListener('hashchange',hash);},[]);return <header className="floating-header"><nav aria-label="主导航"><a href="#home" className="brand" aria-label="樊冰冰 · 首页"><span>BF</span></a><i className="nav-divider"/>{[['#home','Home'],['#work','Work'],['#awards','获奖作品'],['#about','About']].map(([url,label])=><a key={url} className={active===url?'active':''} href={url}>{label}</a>)}<a className="nav-resume" href="/resume.png" target="_blank" rel="noreferrer">Resume ↗</a><i className="nav-divider"/><a className="nav-contact" href="#contact">Say hi <span>↗</span></a></nav></header>}
export function useReveal(pageKey){useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.project, .section-heading, .about>div, .skill-grid article').forEach(el=>{el.classList.add('reveal');observer.observe(el);});return()=>observer.disconnect();},[pageKey])}
