import React, {useEffect,useMemo,useRef,useState} from 'react';
import {normalizeWorkflow} from './workflow-model';
import './workflow.css';

function Graph({workflow}){
 const svg=useRef(null),drag=useRef(null);const [selected,setSelected]=useState(null);
 const bounds=useMemo(()=>{const nodes=workflow.nodes;const x=Math.min(...nodes.map(n=>n.x))-50,y=Math.min(...nodes.map(n=>n.y))-50;return{x,y,w:Math.max(320,Math.max(...nodes.map(n=>n.x+210))-x+50),h:Math.max(200,Math.max(...nodes.map(n=>n.y+84))-y+50)};},[workflow]);
 const [view,setView]=useState(bounds);useEffect(()=>{setView(bounds);setSelected(null);},[bounds]);
 const lookup=useMemo(()=>new Map(workflow.nodes.map(n=>[n.id,n])),[workflow]);
 const zoom=f=>setView(v=>{const w=Math.max(bounds.w*.15,Math.min(bounds.w*4,v.w*f));const ratio=w/v.w;const h=v.h*ratio;return{x:v.x+(v.w-w)/2,y:v.y+(v.h-h)/2,w,h};});
 const start=e=>{if(e.target.closest('[data-node]'))return;svg.current.setPointerCapture(e.pointerId);const rect=svg.current.getBoundingClientRect();const scale=Math.max(view.w/rect.width,view.h/rect.height);drag.current={x:e.clientX,y:e.clientY,view,scale};};
 const move=e=>{if(!drag.current)return;const d=drag.current;setView({...d.view,x:d.view.x-(e.clientX-d.x)*d.scale,y:d.view.y-(e.clientY-d.y)*d.scale});};
 return <div className="graph-shell"><div className="graph-toolbar"><span>{workflow.nodeCount} NODES <i/> {workflow.linkCount} LINKS</span><div><button aria-label="缩小工作流" onClick={()=>zoom(1.3)}>−</button><button onClick={()=>setView(bounds)}>适应画布</button><button aria-label="放大工作流" onClick={()=>zoom(1/1.3)}>+</button></div></div><svg className="workflow-graph" ref={svg} viewBox={`${view.x} ${view.y} ${view.w} ${view.h}`} onPointerDown={start} onPointerMove={move} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} role="group" aria-label="工作流节点画布，可拖动平移或用按钮缩放">{workflow.links.map((l,i)=>{const a=lookup.get(l.from),b=lookup.get(l.to);return <path key={i} className="graph-edge" d={`M ${a.x+210} ${a.y+43} C ${a.x+270} ${a.y+43}, ${b.x-60} ${b.y+43}, ${b.x} ${b.y+43}`}/>;})}{workflow.nodes.map(n=><g data-node="true" key={n.id} role="button" tabIndex={0} aria-label={`查看节点 ${n.label}`} aria-pressed={selected?.id===n.id} className={'graph-node'+(selected?.id===n.id?' selected':'')} transform={`translate(${n.x} ${n.y})`} onClick={()=>setSelected(n)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(n);}}}><rect width="210" height="84" rx="12"/><circle cx="0" cy="43" r="4"/><circle cx="210" cy="43" r="4"/><text x="15" y="24" className="node-number">NODE {n.id.slice(0,16)}</text><text x="15" y="47">{n.label.length>24?n.label.slice(0,22)+'…':n.label}</text><text x="15" y="68" className="node-type">{n.type.slice(0,29)}</text></g>)}</svg><div className="graph-help">拖动画布浏览 · 点击节点查看信息</div>{selected&&<div className="node-inspector"><div><strong>{selected.label}</strong><button aria-label="关闭节点信息" onClick={()=>setSelected(null)}>×</button></div><p>{selected.type}</p><span>输入：{selected.inputs.join(' / ')||'未声明'}</span><span>输出：{selected.outputs.join(' / ')||'未声明'}</span></div>}</div>;
}
const readImage=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('无法读取预览图。'));reader.readAsDataURL(file);});
export function WorkflowLab(){
 const [items,setItems]=useState([]),[current,setCurrent]=useState(null),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[open,setOpen]=useState(false),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[file,setFile]=useState(null),[preview,setPreview]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[success,setSuccess]=useState('');
 const form=useRef(null);const local=import.meta.env.DEV&&['localhost','127.0.0.1'].includes(location.hostname);
 async function refresh(){setLoading(true);setLoadError('');try{const res=await fetch(local?'/__portfolio/workflows':'/workflows/index.json');if(!res.ok)throw Error();const data=await res.json();if(!Array.isArray(data))throw Error();setItems(data);setCurrent(v=>data.some(x=>x.id===v)?v:data[0]?.id||null);}catch{setLoadError('暂时无法读取工作流，请重试。');}finally{setLoading(false);}}
 useEffect(()=>{refresh();},[]);
 useEffect(()=>{if(!loading){const frame=requestAnimationFrame(()=>window.dispatchEvent(new Event('portfolio-content-ready')));return()=>cancelAnimationFrame(frame);}},[loading]);
 async function submit(e){e.preventDefault();setError('');setSuccess('');if(!file)return setError('请先选择 ComfyUI 导出的 JSON 文件。');setBusy(true);try{if(file.size>5*1024*1024)throw Error('工作流不能超过 5 MB。');let raw;try{raw=JSON.parse(await file.text());}catch{throw Error('JSON 文件无法解析，请重新从 ComfyUI 导出。');}normalizeWorkflow(raw);if(preview&&preview.size>6*1024*1024)throw Error('预览图不能超过 6 MB。');const image=preview?await readImage(preview):null;const res=await fetch('/__portfolio/workflows',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,description,workflow:raw,preview:image})});const data=await res.json();if(!res.ok)throw Error(data.error||'保存失败，请重试。');setItems(a=>[data,...a]);setCurrent(data.id);setOpen(false);setTitle('');setDescription('');setFile(null);setPreview(null);form.current?.reset();setSuccess('工作流已保存到网站，刷新后仍可查看。');}catch(e){setError(e.message);}finally{setBusy(false);}}
 const active=items.find(x=>x.id===current);
 return <section className="section workflow-lab" id="workflow"><div className="section-heading"><div><span className="eyebrow">BEHIND THE GENERATION</span><h2>Inside the <em>workflow.</em></h2></div>{local&&<button className="button secondary import-toggle" onClick={()=>{setOpen(v=>!v);setSuccess('');}} aria-expanded={open} aria-controls="workflow-import">{open?'收起导入':'导入工作流'} <span>↗</span></button>}</div><p className="workflow-intro">把一句自然语言需求，连接到可视化方案。<br/>这里展示 ComfyUI 的节点编排、模型调用与生成过程。</p>
 {success&&<p className="form-success" role="status">✓ {success}</p>}
 {open&&<form id="workflow-import" className="workflow-import" ref={form} onSubmit={submit}><div className="import-heading"><h3>添加我的 ComfyUI 工作流</h3><p>文件会保存到此网站的本地项目中。支持工作流 JSON 和 API 格式 JSON；可选添加一张结果图或截图。</p></div><div className="import-fields"><label>工作流文件 <span>JSON · 最大 5 MB</span><input required type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];setFile(f||null);setError('');if(f&&!title)setTitle(f.name.replace(/\.json$/i,''));}}/></label><label>结果图或截图 <span>可选 · PNG / JPG / WebP · 最大 6 MB</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{setPreview(e.target.files?.[0]||null);setError('');}}/></label><label>工作流名称<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} placeholder="例如：苏州街巷空间生成"/></label><label>用途与实现说明<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={1500} rows={3} placeholder="解决什么问题？使用了哪些模型或关键节点？"/></label></div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="import-footer"><span>仅展示工作流，不会在网站上执行模型。</span><button className="button primary" disabled={busy} type="submit">{busy?'正在保存…':'保存并展示'} <span>↑</span></button></div></form>}
 {loading?<div className="workflow-loading" role="status">正在读取工作流…</div>:loadError?<div className="workflow-loading" role="alert">{loadError}<button onClick={refresh}>重试</button></div>:active?<div className="workflow-library"><div className="workflow-tabs" aria-label="选择工作流">{items.map(item=><button key={item.id} aria-pressed={item.id===current} onClick={()=>setCurrent(item.id)}>{item.title}</button>)}</div><div className="workflow-detail"><div className="workflow-detail-heading"><div><span className="eyebrow">{active.format}</span><h3>{active.title}</h3><p>{active.description||'浏览节点之间的连接，了解工作流的组织方式。'}</p></div><a className="download-workflow" href={active.file} download={`${active.title}.json`}>下载 JSON ↓</a></div><Graph key={active.id} workflow={active}/>{active.preview&&<figure className="workflow-result"><img src={active.preview} alt={`${active.title}的结果图或工作流截图`} loading="lazy"/><figcaption>结果图 / 工作流截图</figcaption></figure>}</div></div>:<div className="workflow-concept"><div className="concept-top"><span>城市空间智能辅助系统</span><span>方案逻辑示意</span></div><div className="concept-steps">{[['01','理解需求','自然语言输入'],['02','语义转译','DeepSeek · Prompt'],['03','视觉生成','LoRA · ComfyUI'],['04','应用反馈','小程序交互']].map(([n,t,s])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{s}</p></div>)}</div><div className="concept-bottom"><p>当前为项目方案示意，尚未导入实际工作流文件。</p>{local&&<button className="text-button" onClick={()=>setOpen(true)}>添加第一个工作流 ↗</button>}</div></div>}
 </section>;
}
